name: PR

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Dependencies
        run: |
          npm install
          npm install react
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
